'use strict';
(()=>{
const $=id=>document.getElementById(id),root=new URL('../../',location.href),q=new URLSearchParams(location.search);let data,serial=0;
const text=(el,s)=>el.textContent=s;
function options(el,rows,selected){el.replaceChildren(...rows.map(([value,label])=>new Option(label,value)));if(rows.some(r=>r[0]===selected))el.value=selected;}
async function json(path){const r=await fetch(new URL(path,root),{cache:'no-store'});if(!r.ok)throw Error('Forecast data unavailable');return r.json();}
function draw(){const w=data.windows.find(w=>w.id===$('window').value);if(!w)throw Error('No forecast window');const v=w.regions[$('region').value];$('map').src=new URL(v.path,root);$('map').alt=`Raw HRRR and ANN-CSGD rainfall, ${w.valid_start} to ${w.valid_end}`;$('map').hidden=false;$('full').href=$('map').src;$('full').hidden=false;text($('status'),`Initialized ${data.init} UTC · Valid ${w.valid_start} → ${w.valid_end} · Rainfall in inches`);const body=$('stats').querySelector('tbody');body.replaceChildren();for(const [label,s]of [['Raw HRRR',v.raw],['ANN-CSGD expected',v.ann]]){const tr=document.createElement('tr');for(const value of s?[label,`${s.max_inches.toFixed(3)} in (${s.max_mm.toFixed(1)} mm)`,`${s.latitude.toFixed(2)}, ${s.longitude.toFixed(2)}`,`${s.other_at_max_inches.toFixed(3)} in`,s.points_ge_7_inches,s.points_ge_10_inches]:[label,'No valid points','','','','']){const td=document.createElement('td');td.textContent=value;tr.append(td);}body.append(tr);}$('stats').hidden=false;const url=new URL(location.href);url.searchParams.set('init',data.init);url.searchParams.set('duration',$('duration').value+'h');url.searchParams.set('window',w.window);history.replaceState(null,'',url);}
function windows(){const rows=data.windows.filter(w=>String(w.duration_hours)===$('duration').value).map(w=>[w.id,w.window+' · '+w.valid_start.slice(5,16).replace('T',' ')+' → '+w.valid_end.slice(5,16).replace('T',' ')]);options($('window'),rows,`${$('duration').value}h_${q.get('window')||'f00_f24'}`);draw();}
async function load(){const token=++serial;$('map').hidden=$('stats').hidden=true;try{const loaded=await json(`data/forecast-comparison/raw/${$('run').value}.json`);if(token!==serial)return;data=loaded;$('report').href=new URL(`data/forecast-comparison/raw/${data.init}.json`,root);$('report').hidden=false;windows();}catch(e){text($('status'),e.message);}}
$('run').onchange=load;$('duration').onchange=windows;$('window').onchange=draw;$('region').onchange=draw;
json('data/forecast-comparison/raw/catalog.json').then(c=>{if(!c.runs.length)throw Error('No rainfall comparisons published');options($('run'),c.runs.map(r=>[r.init,r.init.slice(0,8)+' · '+r.init.slice(-2)+'Z']),q.get('init'));const d=(q.get('duration')||'24h').replace('h','');if(['6','12','24'].includes(d))$('duration').value=d;return load();}).catch(e=>text($('status'),e.message));
})();
